package com.hukuton.longoidotulunkristianpcs;

/**
 * Created by Alixson on 27-Mar-16.
 */
public class ListValues {

    public final static String[] LONGOI_SECTION = {
            "Longoi Do Mongohormat",                            // 1 - 21
            "Longoi Do Kinosinaan Di Yesus",                    // 22 - 37
            "Longoi Do Kinapagasan Om Kinapatazan Di Yesus ",   // 38 - 44
            "Longoi Do Kinogulianan Di Yesus",                  // 45 - 49
            "Longoi Do Kinendakadan Di Yesus",                  // 50 - 51
            "Longoi Do Kinendohuan Di Sundu Dot Osusi",         // 52 - 55
            "Longoi Do Mangasip",                               // 56 - 85
            "Longoi Dot Adau-Sodop",                            // 86 - 97
            "Longoi Do Piniizaan",                              // 98 - 100
            "Longoi Do Kapanahakan Om Koponorimakasihan",       // 101 - 104
            "Longoi Minta Berkat",                              // 105 - 106
            "Longoi Do Vagu"                                    // 107 - 121

    };

    public final static int[][] LONGOI_SECTION_NUMBER = {
            {1, 21},
            {22, 37},
            {38, 44},
            {45, 49},
            {50, 51},
            {52, 55},
            {56, 85},
            {86, 97},
            {98, 100},
            {101, 104},
            {105, 106},
            {107, 121}
    };

    public final static String[] LONGOI = {
            "1. Humormat do Kinoringan",
            "2. Siti-kou-no pongoguna",
            "3. Antad sid kosilahon",
            "4. Kohormatan sid Tuhan-za",
            "5. Unsopot tokou sokoviai",
            "6. Pongindazou-no di Yesus",
            "7. O riniba, mongohormat",
            "8. Miumpug tokou tumoguvang",
            "9. Haleluya, haleluya, Amin",
            "10. Humormat dit Ama om it Anak",
            "11. Kohormatan sid Kinoringan",
            "12. O vinangun sokoviai",
            "13. O riniba razou-kou di Tuhan",
            "14. Pongindazou-kou di Tuhan",
            "15. O Tuhan't asavat",
            "16. Banalko osusi ong i Kinoringan",
            "17. Sokoviai i riniba",
            "18. Monorima kaseh sid Kinoringan",
            "19. Humormat dit Ama om i kuasa dau",
            "20. O Tuhan-ku ong itungon-ku kavi",
            "21. O Kinoringan dot asavat",
            "22. Hosiana i raja",
            "23. I korimbutuon Yesus",
            "24. Porikotono it ompiling-nu",
            "25. Antad sid surga mindahu",
            "26. Rumikot-ne Tuhan do mamasi dohon",
            "27. Ot ongoulun Kristian",
            "28. Rikot-kou, pongindazou kou",
            "29. Sid Baitlahim sino-no it anak",
            "30. Imatai i minananggung",
            "31. Antad sorid kosilahon",
            "32. Ot anganak kavi sumiti tokou",
            "33. I sodop't osusi anavau",
            "34. Sid saralom susumadan",
            "35. I malaikat’d Kinoringan",
            "36. Ohigak-ne pomogunan",
            "37. Iningo-ne malaikat",
            "38. Imatai tokou i Yesus",
            "39. Yesus, mongitung-oku",
            "40. O riniba timpan-kou",
            "41. Yesus Tuhan dahai",
            "42. Ot ongoulun Kristian",
            "43. O Tuhan Yesus, nunu i sala nu?",
            "44. I raha di Tuhan Yesus",
            "45. I Tuhan nakamanang-no",
            "46. Nensibak sid lobong i Minananggung",
            "47. Mongindazou-okoi dikau",
            "48. Sumilau-ogi it adau",
            "49. Kristus o nogulianan",
            "50. Yesus Kristus mangahatul",
            "51. Nokendakod-no sid surga",
            "52. Ot ongoulun, unsopot tokou-no",
            "53. Boros do Kinoringan",
            "54. O Tuhan Yesus sid surga",
            "55. O vinangun sokoviai",
            "56. Kinoringan manaud dohon",
            "57. I Tuhan Yesus o minananggung",
            "58. Isai nopo mangasip dohon",
            "59. Nemot-ku no i kosianan",
            "60. Otomon i ginavo-za",
            "61. Minsomok-oku-no sid Tuhan-ku",
            "62. Otomon i ginavo-ku",
            "63. Samadan do Kinoringan",
            "64. Ot Ama dot Osusi sid saralom",
            "65. I Kinoringan banal manamod",
            "66. Kasip-oku sid Kinoringan",
            "67. I Yesus koruhang tokou",
            "68. Ong mozo di Tuhan",
            "69. Ododos iti rahat",
            "70. I samod do Kinoringan",
            "71. Mangasip-oku dot inantakan-oku",
            "72. Boros di Yesus sirid otuvong",
            "73. Nokorikot-kou-no-ka sid di Yesus",
            "74. I dolou-nu Tuhan o mongodim",
            "75. Hondomo i Tuhan Yesus",
            "76. Mangakun-oku Tuhan",
            "77. Aso harapan-ku vokon",
            "78. O Yesus sianai-oku",
            "79. Tuhan Ama do riniba sianai-okoi-no",
            "80. Tulungai-okoi o Tuhan",
            "81. Ot ongoulun Kristian",
            "82. Iso-no kopihatan",
            "83. I Tuhan o mozo-vozo",
            "84. Onom't adau nakatalib",
            "85. Gazado-okoi, Tuhan",
            "86. Yesus Kristus Tuhan tokou",
            "87. Adau darun barat om kavut",
            "88. Kosilahon om kotonobon",
            "89. Intoron sid dohon o Tuhan ku",
            "90. Nokosilau-no it adau",
            "91. Sodop biano modop-okoi",
            "92. Mongindazou-kou",
            "93. Suvab, suvab nga mimbulai",
            "94. Kada kilombusoi, intoron no",
            "95. Nakatalib it sodop",
            "96. I Kinoringan sid surga",
            "97. O Tuhan Yesus ikau-no panganavau",
            "98. I Tuhan Yesus popiizo di tokou",
            "99. Jodizo okoi-no o Kinoringan",
            "100. Barkatai-no Tuhan i piniizaan",
            "101. Nokorikot-no didino it ontok kamatan",
            "102. O vinangun mongindazou-nopo di Kinoringan",
            "103. Ontok didino apatut dot otomon tokou-no",
            "104. Itahak-ku sokoviai sid Tuhan Yesus Kristus",
            "105. O Tuhan berkatai-Okoi-no",
            "106. Tuhan o mozo vozo dikau",
            "107. Monorima kaseh tokou sid Tuhan",
            "108. Ihimo-no dikou i Karajaan",
            "109. Mongindazou tokou-no",
            "110. Kristus amu monodiri",
            "111. Siombo i samod om kabanaran",
            "112. Imatai-no i gama di Tuhan",
            "113. O Yesus Kristus sid ngaran-nu",
            "114. O Tuhan gazado-oku-no",
            "115. I Kinoringan ot ovud",
            "116. Ot ongobansa, pangarazou-kou",
            "117. Ong duvo, tolu miumpug sid ngaran-nu",
            "118. O Tuhan, popiandus-no",
            "119. Siti-no, Tuhan, berkatai-okoi-no",
            "120. Higak sid ngaran di Tuhan",
            "121. Mongining-okoi dikau o Tuhan" };

    public final static String[] ZABUR = {
            "1. I Kosinangan Dot Otopot",
            "2. I Raja Di Tuhan",
            "6. Pokitulungan",
            "8. I Kohormatan Do Kinoringan Om I Guna Do Riniba",
            "12. I Boros Dot Atantu",
            "13. It Ulun Dit Iseso Banal",
            "16. Ikau-No Monuduk Di Ralan Do Koposizan",
            "19. Kogozoo Di Kinourugan Om I Pinonuhuan Do Kinoringan",
            "22. Kosopulan Antad Sid Kosompitan Dot Agazo",
            "23. I Tuhan It Avantang O Panaud",
            "24. Sumuvang Sid Panambayangan",
            "42. It Ulun Di Narakop Lumangad Do Kinoringan",
            "43. Banaro Oku No O Kinoringan",
            "51. I Gama Mindamo Di Kaadaan Do Sala",
            "73. Kakali Mozo-Vozo-Oku Dikau",
            "90. Riniba Obimpasa, Topot Ong Kinoringan Sampai Penlaid",
            "93. I Tuhan O Raja Do Penlaid",
            "95. Mongindazou Di Tuhan",
            "98. I Tuhan Di Sompomogunan Monunda Di Bansa Dau",
            "100. Bansa Tokou Di Tuhan",
            "103. I Pomintaan Dua Do Monorima Kaseh",
            "117. Mongindazou Do Kinoringan",
            "121. I Tuhan O Mozo-Vozo",
            "126. Mokitulung Sid Tanga Do Kosusaan",
            "127. I Barakat Do Kinoringan O Puun Do Kosinangan",
            "130. Pomintaan Dua Sid Kotuvangan",
            "137. Korudu Di Narakop Sid Babel",
            "139. Kotutun I Kinoringan Di Kobuatano-Ku Mantadko Ioku Kondiri",
            "146. I Kinoringan Mangapad Dit Ulun Dot Okugui",
            "148. It Avan Om Tana Nga Mongindazou Di Kinoringan",
            "150. Sokoviai Mongindazou Di Tuhan"
    };

    public final static String[] HOTURAN_SUMAMBAYANG = {
            "Hoturan Sumambayang Adau Minggu",
            "Hoturan Sumambayang Ontok-ko I Kinosinaan Di Tuhan Yesus",
            "Hoturan Sumambayang Do Mongohondom Di Kinapagasan Di Tuhan Yesus",
            "Hoturan Sumambayang Ontok I Kinapatazan Di Tuhan Yesus",
            "Hoturan Sumambayang Ontok Adau Kinogulianan Di Tuhan Yesus Sid Pangalabangan",
            "Hoturan Sumambayang Kinogulianan Di Tuhan Yesus",
            "Hoturan Sumambayang Adau Kinensavatan Di Tuhan Yesus",
            "Hoturan Sumambayang Kinendohuan Di Sundu Dot Osusi",
            "Hoturan Do Sumambayang Ontok Ko I Poginakanan Di Tuhan Yesus",
            "Hoturan Sumambayang Do Mongolobong",
            "Hoturan Sumambayang Adau Kamatan",
            "Hoturan Do Sumambayang Ontok Momodsu Ko Konfirmasi",
            "Hoturan Sumambayang: Posuvang do Ponulung Sid Tumpuk(Baru)",
            "Hoturan Do Sumambayang Anganak",
            "Hoturan Mamarkat Mogontong Hari Minggu",
            "Hoturan Mamarkat Mogontong",
            "Hoturan Sumambayang Perasmian Do Gorija",
            "Hoturan Sumambayang Posuvang Sid Do Kristian",
            "Hoturan Sumambayang Sid Ongo Ongkob",
            "Hoturan Sumambayang Pengucapan Syukur",
            "Liturgi Kebaktian Hari Minggu",
            "Liturgi Acara Perkahwinan Pada Hari Minggu",
            "Liturgi Acara Perkahwinan Pada Hari Biasa",
            "Tatacara Kebaktian Rumah Tangga"
    };

    public final static String[] ONGOVOKON = {

            "I Kosipan dot Ulun Kristian",
            "I Pinonuhuan dot Asamod",
            "I Hopod Pinonuhuan",
            "Ongo Ayat Barkat",
            "Tudukan Do Kopomodsuan"
    };

    public final static int[] getOngovokonStringIDs = {
            R.string.ovkn_kosipan,
            R.string.ovkn_asamod,
            R.string.ovkn_kosipan_10_pinonuhuan,
            R.string.ovkn_ayat_barkat,
            R.string.ovkn_tudukan_kopomodsuan
    };

    public final static String[] POMINTAAN_DUA = {
            "I Pomintaan Dua di Tuhan Yesus",
            "Pomintaan Dua do Minggu",
            "Pomintaan Dua Sumungkad di Tuturan",
            "Pomintaan Dua Ontok Adau do Kibantug(Advent)",
            "Pomintaan Dua Ontok Kembulazan(Epiphany) do Toun",
            "Pomintaan Dua Minggu Gulu Kinapatazan di Tuhan Yesus",
            "Pomintaan Doa Sumungkad Di Tuturan Kinapagasan di Tuhan Yesus",
            "Pomintaan Dua Ontok Adau Kinogulianan di Tuhan Yesus",
            "Pomintaan Dua Ontok Kininsavatan di Tuhan Yesus",
            "Pomintaan Dua Ontok Pentakosta",
            "Pomintaan Dua Ontok Adau Trinity",
            "Pomintaan Dua dot Ontok Pensubaan",
            "Pomintaan Dua do Varo Minatai",
            "Pomintaan Dua do Kalandai ot Anak",
            "Pomintaan Dua Ontok dot Agazo o Kotulungan",
            "Pomintaan Dua di Sodop do Hari Anam",
            "Pomintaan Dua do Sasarap do Minggu",
            "Pomintaan Dua di Sodop do Minggu",
            "Pomintaan Dua do Monginakan",
            "Pomintaan Dua do Mongontok di Sumakit",
            "Pomintaan Dua do Sasarap",
            "Pomintaan Dua do Sosodop"};

    public final static int[] getPomintaanDuaIDs = {
            R.string.doa_di_tuhan_yesus,
            R.string.doa_do_minggu,
            R.string.doa_sumungkad_tuturan,
            R.string.doa_ontok_kibantug,
            R.string.doa_ontok_kembulazan,
            R.string.doa_kinapatazan_tuhan_yesus,
            R.string.doa_tuturan_kinapagasan_tuhan_yesus,
            R.string.doa_kinogulianan_tuhan_yesus,
            R.string.doa_kininsavatan_tuhan_yesus,
            R.string.doa_pentakosta,
            R.string.doa_trinity,
            R.string.doa_ontok_pensubaan,
            R.string.doa_varo_minatai,
            R.string.doa_kalandai_anak,
            R.string.doa_kotulungan,
            R.string.doa_sodop_hari_anam,
            R.string.doa_sasarap_minggu,
            R.string.doa_sodop_minggu,
            R.string.doa_monginakan,
            R.string.doa_mongontok_sumakit,
            R.string.doa_sasarap,
            R.string.doa_sosodop
    };
    /*
        public final static int[] getHoturanLayoutIDs = {
                R.layout.hs_fragment_h1,
                R.layout.hs_fragment_h2,
                R.layout.hs_fragment_h3,
                R.layout.hs_fragment_h4,
                R.layout.hs_fragment_h5,
                R.layout.hs_fragment_h6,
                R.layout.hs_fragment_h7,
                R.layout.hs_fragment_h8,
                R.layout.hs_fragment_h9,
                R.layout.hs_fragment_h10,
                R.layout.hs_fragment_h11,
                R.layout.hs_fragment_h12,
                R.layout.hs_fragment_h13,
                R.layout.hs_fragment_h14,
                R.layout.hs_fragment_h15,
                R.layout.hs_fragment_h16,
                R.layout.hs_fragment_h17,
                R.layout.hs_fragment_h18,
                R.layout.hs_fragment_h19,
                R.layout.hs_fragment_h20,
        };
    */
    public final static int[] getZaburStringIDs = {
            R.string.zabur_1,
            R.string.zabur_2,
            R.string.zabur_6,
            R.string.zabur_8,
            R.string.zabur_12,
            R.string.zabur_13,
            R.string.zabur_16,
            R.string.zabur_19,
            R.string.zabur_22,
            R.string.zabur_23,
            R.string.zabur_24,
            R.string.zabur_42,
            R.string.zabur_43,
            R.string.zabur_51,
            R.string.zabur_73,
            R.string.zabur_90,
            R.string.zabur_93,
            R.string.zabur_95,
            R.string.zabur_98,
            R.string.zabur_100,
            R.string.zabur_103,
            R.string.zabur_117,
            R.string.zabur_121,
            R.string.zabur_126,
            R.string.zabur_127,
            R.string.zabur_130,
            R.string.zabur_137,
            R.string.zabur_139,
            R.string.zabur_146,
            R.string.zabur_148,
            R.string.zabur_150
    };
}